@extends('layouts.app')

@section('content')
<div class="glass-panel">
    <h2>Alert History</h2>
    <p>Complete log of flood and rainfall alerts generated by the AVN system.</p>

    <table style="width: 100%; border-collapse: collapse; margin-top: 1rem;">
        <thead>
            <tr style="text-align: left; color: var(--secondary-text); border-bottom: 1px solid var(--glass-border);">
                <th style="padding: 1rem;">Time</th>
                <th style="padding: 1rem;">Node</th>
                <th style="padding: 1rem;">Type</th>
                <th style="padding: 1rem;">Severity</th>
                <th style="padding: 1rem;">Message</th>
            </tr>
        </thead>
        <tbody>
            @foreach($alerts as $alert)
            <tr style="border-bottom: 1px solid var(--glass-border);">
                <td style="padding: 1rem;">{{ $alert->triggered_at->toDateTimeString() }}</td>
                <td style="padding: 1rem;">{{ $alert->telemetryNode->name }}</td>
                <td style="padding: 1rem;">{{ strtoupper($alert->type) }}</td>
                <td style="padding: 1rem;">
                    <span style="color: {{ $alert->severity === 'critical' ? '#ef4444' : '#f59e0b' }}; font-weight: bold;">
                        {{ strtoupper($alert->severity) }}
                    </span>
                </td>
                <td style="padding: 1rem;">{{ $alert->message }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection
